# 1. Load the image into memory
preload = ~/Downloads/wallpaper.png

# 2. Set it to a monitor
# Syntax: wallpaper = <monitor>, <path>
# Leaving the monitor empty (",") sets it for ALL monitors
wallpaper = ,~/Downloads/wallpaper.png
